module.exports = {
  apps: [
    {
      name: "solprobe",
      script: "./start.sh",
      interpreter: "bash",
      restart_delay: 3000,
      max_restarts: 20,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      log_file: "logs/combined.log",
      error_file: "logs/error.log",
      time: true,
    },
    {
      name: "solprobe-buyback",
      script: "./scripts/buyback.ts",
      interpreter: "npx",
      interpreter_args: "tsx",
      restart_delay: 10000,
      max_restarts: 10,
      watch: false,
      env: {
        NODE_ENV: "production",
        DRY_RUN: "true",
      },
      log_file: "logs/buyback-combined.log",
      error_file: "logs/buyback-error.log",
      time: true,
    },
    {
      name: "health-watchdog",
      script: "./scripts/healthWatchdog.ts",
      interpreter: "npx",
      interpreter_args: "tsx",
      cron_restart: "*/5 * * * *",
      autorestart: false,
      watch: false,
      log_file: "logs/watchdog-combined.log",
      error_file: "logs/watchdog-error.log",
      time: true,
    },
  ],
};
